export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const CARS = {
    REQUEST:"GET_CARS_REQUEST",
    SUCCESS:"GET_CARS_SUCCESS",
    FAIL:"GET_CARS_FAIL",
}

export const CAR = {
    REQUEST:"GET_CAR_REQUEST",
    SUCCESS:"GET_CAR_SUCCESS",
    FAIL:"GET_CAR_FAIL",
}

export const ADD_TO_CART = "ADD_TO_CART"